// blocks.c
// Defines block types.

#include "blocks.h"

#include "species.h"

/**********************
 * Constants and Data *
 **********************/

// Bits are:
//  0-1: Visibility (visible, invisible, transparent, translucent)
//  2-3: Substance (solid, liquid, empty, obstructed)
//
//  4-7: Geometry (full, half, liquid, grass, etc.)
//
//  8: Anisotropic (different textures for different faces)
//  9: Orientable (can be placed facing multiple directions)
//
//  12: Grows (will be processed by the ecology subsystem)
//  13: Growth site (grows by grammar transformations)
//  14: Growth core (grows using growth particles)
//  15: Aquatic (grows in water instead of air)
//
//  16: Seed (generally more transient)
//
//  19-23: Species type (see species_type_e in species.h)

block_info BLOCK_INFO[TOTAL_BLOCK_TYPES];

char* BLOCK_NAMES[TOTAL_BLOCK_TYPES];

/*********************
 * Private Functions *
 *********************/

void _bdef(
  block id,
  char* name,
  block_info vis,
  block_info sbst,
  block_info geom,
  species_type spt,
  block_info flags
) {
  BLOCK_NAMES[id] = name;
  BLOCK_INFO[id] = (
    (vis << BIMS_VISIBILITY)
  & (sbst << BIMS_SUBSTANCE)
  & (geom << BIMS_GEOMETRY)
  & (spt << BIMS_SPECIES_TYPE)
  & flags
  );
}

/*************
 * Functions *
 *************/

void init_blocks(void) {
// All flags:
// TODO: Keep this up-to-date
//  BIF_ANISOTROPIC
//  BIF_ORIENTABLE
//  BIF_GROWS
//  BIF_GROWTH_SITE
//  BIF_GROWTH_CORE
//  BIF_AQUATIC
//  BIF_SEED

  _bdef( B_VOID, "void",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_NO_SPECIES,
    0);

  _bdef( B_BOUNDARY, "boundary",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_NO_SPECIES,
    0);

  _bdef( B_AIR, "air",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_NO_SPECIES,
    0);
  _bdef( B_ETHER, "ether",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_NO_SPECIES,
    0);

  _bdef( B_FUMES, "fumes",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_GAS,
    0);

  _bdef( B_WATER, "water",
    BI_VIS_TRANSLUCENT,  BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC);
  _bdef( B_WATER_FLOW, "water_flow",
    BI_VIS_TRANSLUCENT,  BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);

  _bdef( B_SLIME, "slime",
    BI_VIS_TRANSLUCENT,  BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC);
  _bdef( B_SLIME_FLOW, "slime_flow",
    BI_VIS_TRANSLUCENT,  BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);

  _bdef( B_ACID, "acid",
    BI_VIS_TRANSLUCENT,  BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC);
  _bdef( B_ACID_FLOW, "acid_flow",
    BI_VIS_TRANSLUCENT,  BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);

  _bdef( B_QUICKSAND, "quicksand",
    BI_VIS_OPAQUE,       BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_STONE,
    BIF_ANISOTROPIC);

  _bdef( B_LAVA, "lava",
    BI_VIS_OPAQUE,       BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_STONE,
    BIF_ANISOTROPIC);
  _bdef( B_LAVA_FLOW, "lava_flow",
    BI_VIS_OPAQUE,       BI_SBST_LIQUID,      BI_GEOM_LIQUID, SPT_STONE,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);

  _bdef( B_SMOKE, "smoke",
    BI_VIS_TRANSLUCENT,  BI_SBST_EMPTY,       BI_GEOM_SOLID,  SPT_GAS,
    0);
  _bdef( B_MIASMA, "miasma",
    BI_VIS_TRANSLUCENT,  BI_SBST_EMPTY,       BI_GEOM_SOLID,  SPT_GAS,
    0);

  _bdef( B_THICK_SMOKE, "thick_smoke",
    BI_VIS_OPAQUE,       BI_SBST_EMPTY,       BI_GEOM_SOLID,  SPT_GAS,
    0);

  _bdef( B_DIRT, "dirt",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_DIRT,
    0);
  _bdef( B_MUD, "mud",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_DIRT,
    0);
  _bdef( B_CLAY, "clay",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_CLAY,
    0);
  _bdef( B_SAND, "sand",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_STONE,
    0);
  _bdef( B_GRAVEL, "gravel",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_STONE,
    0);
  _bdef( B_SCREE, "scree",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_STONE,
    0);
  _bdef( B_STONE, "stone",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_STONE,
    0);
  _bdef( B_NATIVE_METAL, "native_metal",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_METAL,
    0);

  _bdef( B_MUSHROOM_SPORES, "mushroom_spores",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_FUNGUS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_MUSHROOM_SHOOTS, "mushroom_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_FUNGUS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_MUSHROOM_GROWN, "mushroom",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_FUNGUS,
    BIF_GROWS | BIF_GROWTH_SITE);

  _bdef( B_GIANT_MUSHROOM_SPORES, "giant_mushroom_spores",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_FUNGUS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_GIANT_MUSHROOM_CORE, "giant_mushroom_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_FUNGUS,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_GIANT_MUSHROOM_MYCELIUM, "giant_mushroom_mycelium",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_FUNGUS,
    BIF_GROWS);
  _bdef( B_GIANT_MUSHROOM_SPROUT, "giant_mushroom_sprout",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_FUNGUS,
    BIF_GROWS);
  _bdef( B_GIANT_MUSHROOM_STALK, "giant_mushroom_stalk",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_FUNGUS,
    BIF_ANISOTROPIC | BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_GIANT_MUSHROOM_CAP, "giant_mushroom_cap",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_FUNGUS,
    BIF_ANISOTROPIC | BIF_ORIENTABLE | BIF_GROWS);

  _bdef( B_MOSS_SPORES, "moss_spores",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_MOSS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_MOSS_SHOOTS, "moss_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_VINE,   SPT_MOSS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_MOSS_GROWN, "moss",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_MOSS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_MOSS_FLOWERING, "flowering_moss",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_MOSS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_MOSS_FRUITING, "fruiting_moss",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_MOSS,
    BIF_GROWS | BIF_GROWTH_SITE);

  _bdef( B_GRASS_SEEDS, "grass_seeds",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_GRASS_ROOTS, "grass_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_ROOT,   SPT_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_GRASS_SHOOTS, "grass_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_GRASS_GROWN, "grass",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_GRASS_FLOWERING, "flowering_grass",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE);
  _bdef( B_GRASS_FRUITING, "fruiting_grass",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE);

  _bdef( B_VINE_SEEDS, "vine_seeds",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_VINE,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_VINE_CORE, "vine_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_VINE,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_VINE_ROOTS, "vine_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_VINE,
    BIF_GROWS);
  _bdef( B_VINE_SHOOTS, "vine_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_SPROUTING, "sprouting_vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_GROWN, "vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_BUDDING, "budding_vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_FLOWERING, "flowering_vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_FRUITING, "fruiting_vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_SHEDDING, "shedding_vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_VINE_DORMANT, "dormant_vine",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_VINE,   SPT_VINE,
    BIF_ORIENTABLE | BIF_GROWS);

  _bdef( B_HERB_SEEDS, "herb_seeds",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_HERB,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_HERB_CORE, "herb_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_HERB,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_HERB_ROOTS, "herb_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_HERB,
    BIF_GROWS);
  _bdef( B_HERB_SHOOTS, "herb_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_HERB,
    BIF_GROWS);
  _bdef( B_HERB_GROWN, "herb",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_HERB,   SPT_HERB,
    BIF_GROWS);
  _bdef( B_HERB_BUDDING, "budding_herb",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_HERB,   SPT_HERB,
    BIF_GROWS);
  _bdef( B_HERB_FLOWERING, "flowering_herb",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_HERB,   SPT_HERB,
    BIF_GROWS);
  _bdef( B_HERB_FRUITING, "fruiting_herb",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_HERB,   SPT_HERB,
    BIF_GROWS);

  _bdef( B_BUSH_SEEDS, "bush_seeds",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_BUSH,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_BUSH_CORE, "bush_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_BUSH,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_BUSH_ROOTS, "bush_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_SHOOTS, "bush_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_SPROUTING, "sprouting_bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_GROWN, "bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_BUDDING, "budding_bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_FLOWERING, "flowering_bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_FRUITING, "fruiting_bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_SHEDDING, "shedding_bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_BRANCHES_DORMANT, "dormant_bush_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_SPROUTING, "sprouting_bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_GROWN, "bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_BUDDING, "budding_bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_FLOWERING, "flowering_bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_FRUITING, "fruiting_bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_SHEDDING, "shedding_bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);
  _bdef( B_BUSH_LEAVES_DORMANT, "dormant_bush_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_BUSH,
    BIF_GROWS);

  _bdef( B_SHRUB_SEEDS, "shrub_seeds",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_SHRUB,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_SHRUB_CORE, "shrub_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_SHRUB,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_SHRUB_ROOTS, "shrub_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_THICK_ROOTS, "shrub_thick_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_SHOOTS, "shrub_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_SPROUTING, "sprouting_shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_GROWN, "shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_BUDDING, "budding_shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_FLOWERING, "flowering_shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_FRUITING, "fruiting_shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_SHEDDING, "shedding_shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_BRANCHES_DORMANT, "dormant_shrub_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_SPROUTING, "sprouting_shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_GROWN, "shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_BUDDING, "budding_shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_FLOWERING, "flowering_shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_FRUITING, "fruiting_shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_SHEDDING, "shedding_shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);
  _bdef( B_SHRUB_LEAVES_DORMANT, "dormant_shrub_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_SHRUB,
    BIF_GROWS);

  _bdef( B_TREE_SEEDS, "tree_seeds",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_TREE,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED);
  _bdef( B_TREE_CORE, "tree_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_TREE,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_TREE_HEART_CORE, "tree_heart_core",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS | BIF_GROWTH_CORE);
  _bdef( B_TREE_ROOTS, "tree_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_THICK_ROOTS, "tree_thick_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_HEART_ROOTS, "tree_heart_roots",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_SHOOTS, "tree_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_TRUNK, "tree_trunk",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID,  SPT_TREE,
    BIF_ANISOTROPIC | BIF_ORIENTABLE | BIF_GROWS);
  _bdef( B_TREE_BARE_BRANCHES, "tree_bare_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_SPROUTING, "sprouting_tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_GROWN, "tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_BUDDING, "budding_tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_FLOWERING, "flowering_tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_FRUITING, "fruiting_tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_SHEDDING, "shedding_tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_BRANCHES_DORMANT, "dormant_tree_branches",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_SPROUTING, "sprouting_tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_GROWN, "tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_BUDDING, "budding_tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_FLOWERING, "flowering_tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_FRUITING, "fruiting_tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_SHEDDING, "shedding_tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);
  _bdef( B_TREE_LEAVES_DORMANT, "dormant_tree_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_TREE,
    BIF_GROWS);

  _bdef( B_AQUATIC_GRASS_SEEDS, "aquatic_grass_seeds",
    BI_VIS_INVISIBLE,    BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_AQUATIC_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_AQUATIC | BIF_SEED);
  _bdef( B_AQUATIC_GRASS_ROOTS, "aquatic_grass_roots",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_AQUATIC_GRASS,
    BIF_GROWS);
  _bdef( B_AQUATIC_GRASS_SHOOTS, "aquatic_grass_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_AQUATIC_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_AQUATIC);
  _bdef( B_AQUATIC_GRASS_GROWN, "aquatic_grass",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_AQUATIC_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_AQUATIC);
  _bdef( B_AQUATIC_GRASS_FLOWERING, "flowering_aquatic_grass",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_AQUATIC_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_AQUATIC);
  _bdef( B_AQUATIC_GRASS_FRUITING, "fruiting_aquatic_grass",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_GRASS,  SPT_AQUATIC_GRASS,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_AQUATIC);

  _bdef( B_AQUATIC_PLANT_SEEDS, "aquatic_plant_seeds",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_EMPTY,  SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_SEED | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_CORE, "aquatic_plant_core",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_GROWTH_CORE | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_ANCHORS, "aquatic_plant_anchors",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_ROOT,   SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_SHOOTS, "aquatic_plant_shoots",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_HERB,   SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_STEMS, "aquatic_plant_stems",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_LEAVES_GROWN, "aquatic_plant_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_LEAVES_FLOWERING, "flowering_aquatic_plant_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_AQUATIC);
  _bdef( B_AQUATIC_PLANT_LEAVES_FRUITING, "fruiting_aquatic_plant_leaves",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID,  SPT_AQUATIC_PLANT,
    BIF_GROWS | BIF_AQUATIC);

  _bdef( B_YOUNG_CORAL, "young_coral",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_HERB,  SPT_CORAL,
    BIF_GROWS | BIF_GROWTH_SITE | BIF_AQUATIC);
  _bdef( B_CORAL_CORE, "coral_core",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_CORAL,
    BIF_GROWS | BIF_GROWTH_CORE | BIF_AQUATIC);
  _bdef( B_CORAL_BODY, "coral_body",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_CORAL,
    BIF_GROWS | BIF_AQUATIC);
  _bdef( B_CORAL_FROND, "coral_frond",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_SOLID, SPT_CORAL,
    BIF_GROWS | BIF_AQUATIC);

  _bdef( B_SMOOTHED_ROCK, "smoothed_rock",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);
  _bdef( B_HEWN_ROCK_GRATE, "hewn_rock_grate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_FENCE, SPT_STONE,
    BIF_ORIENTABLE);

  _bdef( B_BALE, "bale",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_HERB,
    0);
  _bdef( B_THATCH, "thatch",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_HERB,
    0);
  _bdef( B_WATTLE, "wattle",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_FENCE, SPT_TREE,
    BIF_ORIENTABLE); // TODO: Species type for wattle!

  _bdef( B_WOODEN_PLANK, "wooden_plank",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_TREE,
    0);
  _bdef( B_WOODEN_BEAM, "wooden_beam",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_BEAM,  SPT_TREE,
    0);
  _bdef( B_WOODEN_PANEL, "wooden_panel",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_TREE,
    BIF_ORIENTABLE);
  _bdef( B_WOODEN_PILLAR, "wooden_pillar",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_COLUMN,SPT_TREE,
    0);

  _bdef( B_CORDWOOD, "cordwood",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_TREE,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);
  _bdef( B_COB, "cob",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_CLAY,
    0); // TODO: Species type for multi-species construction materials?
  _bdef( B_RAMMED_EARTH, "rammed_earth",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_DIRT,
    0);
  _bdef( B_STACKED_STONE, "stacked_stone",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);
  _bdef( B_FITTED_STONE, "fitted_stone",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);
  _bdef( B_MORTARED_STONE, "mortared_stone",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);
  _bdef( B_METAL_BARS, "metal_bars",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_FENCE, SPT_METAL,
    BIF_ORIENTABLE);
  _bdef( B_STONE_POST, "stone_post",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_BEAM,  SPT_STONE,
    0);
  _bdef( B_STONE_PILLAR, "stone_pillar",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_COLUMN,SPT_STONE,
    0);
  _bdef( B_MUD_BRICK, "mud_brick",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_DIRT,
    0);
  _bdef( B_CLAY_BRICK, "clay_brick",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_CLAY,
    0);
  _bdef( B_STONE_BRICK, "stone_brick",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);

  _bdef( B_WOODEN_SHINGLE, "wooden_shingle",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_TREE,
    BIF_ORIENTABLE);
  _bdef( B_STONE_TILE, "stone_tile",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_STONE,
    BIF_ORIENTABLE);
  _bdef( B_CERAMIC_TILE, "ceramic_tile",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_CLAY,
    BIF_ORIENTABLE);

  _bdef( B_WOODEN_GRATE, "wooden_grate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_FENCE, SPT_TREE,
    BIF_ORIENTABLE);
  _bdef( B_STONE_GRATE, "stone_grate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_FENCE, SPT_STONE,
    BIF_ORIENTABLE);
  _bdef( B_METAL_GRATE, "metal_grate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_FENCE, SPT_METAL,
    BIF_ORIENTABLE);

  _bdef( B_GLASS_BLOCK, "glass_block",
    BI_VIS_TRANSLUCENT,  BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);
  _bdef( B_GLASS_PANE, "glass_pane",
    BI_VIS_TRANSLUCENT,  BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_STONE,
    0);

  _bdef( B_WOODEN_EDGING, "wooden_edging",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_TREE,
    0);
  _bdef( B_STONE_EDGING, "stone_edging",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_STONE,
    0);
  _bdef( B_METAL_EDGING, "metal_edging",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_METAL,
    0);

  _bdef( B_WOODEN_FRAME, "wooden_frame",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_TREE,
    BIF_ORIENTABLE);
  _bdef( B_STONE_FRAME, "stone_frame",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_STONE,
    BIF_ORIENTABLE);
  _bdef( B_METAL_FRAME, "metal_frame",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_METAL,
    BIF_ORIENTABLE);

  _bdef( B_METAL_BLOCK, "metal_block",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_SOLID, SPT_METAL,
    0);

  _bdef( B_WOODEN_GATE, "wooden_gate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_TREE,
    BIF_ORIENTABLE);
  _bdef( B_STONE_GATE, "stone_gate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_STONE,
    BIF_ORIENTABLE);
  _bdef( B_METAL_GATE, "metal_gate",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_METAL,
    BIF_ORIENTABLE);

  _bdef( B_WOODEN_PLANK_DOOR, "wooden_plank_door",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_TREE,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);
  _bdef( B_WOODEN_PANEL_DOOR, "wooden_panel_door",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_TREE,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);
  _bdef( B_STONE_DOOR, "stone_door",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_STONE,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);
  _bdef( B_METAL_DOOR, "metal_door",
    BI_VIS_TRANSPARENT,  BI_SBST_SOLID,       BI_GEOM_DOOR,  SPT_METAL,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);

  _bdef( B_PLASTER, "plaster",
    BI_VIS_OPAQUE,       BI_SBST_EMPTY,       BI_GEOM_FILM,  SPT_STONE,
    0);
  _bdef( B_STUCCO, "stucco",
    BI_VIS_OPAQUE,       BI_SBST_EMPTY,       BI_GEOM_FILM,  SPT_STONE,
    0);
  _bdef( B_PAINT, "paint",
    BI_VIS_OPAQUE,       BI_SBST_EMPTY,       BI_GEOM_FILM,  SPT_PIGMENT,
    0);

  // TODO: Pigmentation / patterns?!?
  _bdef( B_BANNER, "banner",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_PANEL, SPT_FIBER,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);
  _bdef( B_TAPESTRY, "tapestry",
    BI_VIS_TRANSPARENT,  BI_SBST_OBSTRUCTED,  BI_GEOM_PANEL, SPT_FIBER,
    BIF_ANISOTROPIC | BIF_ORIENTABLE);
  _bdef( B_PAINTING, "painting",
    BI_VIS_OPAQUE,       BI_SBST_SOLID,       BI_GEOM_PANEL, SPT_PIGMENT,
    BIF_ANISOTROPIC | BIF_ORIENTABLE); // TODO: Species for paintings?
  _bdef( B_ENGRAVING, "engraving",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_SOLID, SPT_NO_SPECIES,
    BIF_ANISOTROPIC | BIF_ORIENTABLE); // TODO: Species for engravings?

  _bdef( B_CARPET, "carpet",
    BI_VIS_OPAQUE,       BI_SBST_EMPTY,       BI_GEOM_PANEL, SPT_FIBER,
    BIF_ORIENTABLE);
  _bdef( B_RUG, "rug",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_PANEL, SPT_FIBER,
    BIF_ORIENTABLE);
  _bdef( B_STEM_MAT, "stem_mat",
    BI_VIS_TRANSPARENT,  BI_SBST_EMPTY,       BI_GEOM_PANEL, SPT_HERB,
    BIF_ORIENTABLE);
}
